#!/usr/bin/env python3
"""Generate lib/l10n/app_*.arb from embedded English master + per-locale overrides."""

import copy
import json
import os

DIR = os.path.join(os.path.dirname(__file__), "..", "lib", "l10n")

EN = {
    "@@locale": "en",
    "appTitle": "Verdant",
    "brandName": "Verdant",
    "account": "Account",
    "searchHint": "Search…",
    "userFallback": "U",
    "back": "Back",
    "next": "Next",
    "done": "Done",
    "forward": "Continue",
    "save": "Save",
    "or": "or",
    "yes": "Yes",
    "no": "No",
    "faqTitle": "FAQ",
    "monthly": "Monthly",
    "yearlyWithDiscount": "Yearly (-20%)",
    "billing": "Billing",
    "perMonth": "/month",
    "perMonthAnnual": "/month (billed annually)",
    "langName_en": "English",
    "langName_it": "Italian",
    "langName_fr": "French",
    "langName_de": "German",
    "langName_zh": "Chinese",
    "langName_ru": "Russian",
    "langName_uk": "Ukrainian",
    "langName_he": "Hebrew",
    "langName_fa": "Persian",
    "langName_es": "Spanish",
    "langName_pt": "Portuguese",
    "langName_ar": "Arabic",
    "langName_ja": "Japanese",
    "langName_ko": "Korean",
    "langName_nl": "Dutch",
    "langName_pl": "Polish",
    "langName_tr": "Turkish",
    "langName_hi": "Hindi",
    "langName_sv": "Swedish",
    "langName_el": "Greek",
    "language": "Language",
    "navDashboard": "Dashboard",
    "navEmissions": "Data & emissions",
    "navReports": "ESG reports",
    "navCompliance": "Compliance",
    "navIntegrations": "Integrations",
    "navSettings": "Settings",
    "navShortDashboard": "Dashboard",
    "navShortData": "Data",
    "navShortReports": "Reports",
    "navShortCompliance": "Compliance",
    "navShortIntegrations": "Apps",
    "planStarterSidebar": "Starter plan",
    "reportsUsedProgress": "{used}/{total} reports used",
    "@reportsUsedProgress": {"placeholders": {"used": {}, "total": {}}},
    "upgradeGrowth": "Upgrade to Growth",
    "landingFeatures": "Features",
    "landingPricing": "Pricing",
    "landingLogin": "Log in",
    "landingTryFree": "Start free trial",
    "heroHeadline": "ESG compliance\nin 5 minutes.\nNot in 5 months.",
    "heroSub": "Verdant automatically calculates your CO₂ emissions, generates CSRD‑ready reports, and helps you reduce regulatory risk.",
    "heroCtaFree": "Start free — 14 days",
    "heroCtaDemo": "Watch demo →",
    "heroBadgeCsrd": "CSRD 2025 ready",
    "heroSocialProof": "Already used by 340+ European SMEs",
    "heroEsgScore": "ESG score",
    "heroScore": "{current} / {max}",
    "@heroScore": {"placeholders": {"current": {}, "max": {}}},
    "heroScopeCsrd": "CSRD ✓",
    "heroScope1": "Scope 1 ✓",
    "heroScope2": "Scope 2 ✓",
    "problemTitle": "The ESG chaos you have today",
    "problem1Title": "Data everywhere",
    "problem1Body": "Spreadsheets, email, PDFs, ERP — no single system for metrics.",
    "problem2Title": "Opaque standards",
    "problem2Body": "CSRD, ISSB, GRI, CDP — a different language every time.",
    "problem3Title": "€200/h consultants",
    "problem3Body": "For reports that law changes every year.",
    "problemWarning": "From 2026 CSRD penalties can reach up to 2% of turnover",
    "solutionTitle": "Everything you need. Nothing you don’t.",
    "solTabCo2": "📊 Calculate CO₂",
    "solTabReport": "📄 Generate reports",
    "solTabAlerts": "🔔 Regulatory alerts",
    "solTabIntegrate": "🔌 Integrate systems",
    "solCo2Kwh": "kWh electricity",
    "solCo2KwhHint": "e.g. 125000",
    "solCo2Diesel": "Diesel litres",
    "solCo2DieselHint": "e.g. 4200",
    "solCo2Km": "Transport km",
    "solCo2KmHint": "e.g. 180000",
    "solCo2Estimate": "Scope 1: {tons} t CO₂ (demo estimate)",
    "@solCo2Estimate": {"placeholders": {"tons": {}}},
    "solReportPreviewTitle": "Report preview",
    "solReportPreviewBody": "CSRD • Executive summary\nLogo • Digital signature",
    "solReportExportDemo": "Export PDF (demo)",
    "snackDownloadSimulated": "Simulated download",
    "solAlert1": "By Dec 2025: first CSRD reporting",
    "solAlert2": "Scope 3: request from automotive OEM",
    "solAlert3": "ISSB template update available",
    "severityCritical": "Critical",
    "severityAttention": "Warning",
    "severityInfo": "Info",
    "integNameSap": "SAP",
    "integNameExcel": "Excel",
    "integNameQuickbooks": "QuickBooks",
    "integNameFic": "Cloud invoicing",
    "integNameSheets": "Google Sheets",
    "integNameApi": "Custom API",
    "integStatusConnected": "Connected ✓",
    "integStatusAvailable": "Available",
    "integStatusSoon": "Coming soon",
    "socialTitle": "What SMEs say about Verdant",
    "socialMetricCompanies": "340+ companies",
    "socialMetricCompliance": "98% compliance rate",
    "socialMetricSavings": "€180k avg. consultant savings",
    "socialMetricRating": "4.9★ rating",
    "testimonial1Name": "Mario R.",
    "testimonial1Role": "CFO • Metaltech Srl",
    "testimonial1Quote": "We answered Stellantis’ EcoVadis questionnaire in 2 days. It used to take 3 weeks.",
    "testimonial2Name": "Laura M.",
    "testimonial2Role": "Sustainability Manager • SME",
    "testimonial2Quote": "Finally a tool built for SMEs. Not SAP, not Workiva. Verdant.",
    "testimonial3Name": "Giorgio B.",
    "testimonial3Role": "Accountant • Firm",
    "testimonial3Quote": "I manage 12 SME clients in one account. Immediate ROI.",
    "pricingTransparent": "Transparent pricing",
    "pricingSubtitle": "Pick a plan and scale with your company.",
    "pricingBilling": "Billing",
    "pricingEnterprise": "Enterprise with 1000+ employees? Contact us for custom pricing.",
    "pricingPaySecure": "Secure payment via Stripe • e‑invoicing included",
    "pricingPayVisa": "VISA",
    "pricingPayMc": "MC",
    "pricingPayStripe": "Stripe",
    "planStarter": "Starter",
    "planGrowth": "Growth",
    "planPartner": "Partner",
    "planBadgePopular": "Most popular",
    "planBadgePartner": "For consultants & firms",
    "planCtaStartTrial": "Start 14‑day free trial",
    "planCtaContactSales": "Contact sales",
    "planStarterF1": "✓ 1 company site",
    "planStarterF2": "✓ CO₂ Scope 1 & 2",
    "planStarterF3": "✓ 3 ESG reports/year",
    "planStarterF4": "✓ Basic CSRD templates",
    "planStarterF5": "✓ PDF export",
    "planStarterF6": "✗ Scope 3 (suppliers)",
    "planStarterF7": "✗ API access",
    "planStarterF8": "✗ Multi‑site",
    "planGrowthF1": "✓ Everything in Starter",
    "planGrowthF2": "✓ Multi‑site (up to 5)",
    "planGrowthF3": "✓ Scope 3 supply chain",
    "planGrowthF4": "✓ Unlimited reports",
    "planGrowthF5": "✓ CSRD + ISSB + CDP",
    "planGrowthF6": "✓ Automatic regulatory alerts",
    "planGrowthF7": "✓ Advanced Excel integration",
    "planGrowthF8": "✓ Sector benchmark dashboard",
    "planGrowthF9": "✗ API access",
    "planGrowthF10": "✗ White label",
    "planPartnerF1": "✓ Everything in Growth",
    "planPartnerF2": "✓ Unlimited clients",
    "planPartnerF3": "✓ Full API access",
    "planPartnerF4": "✓ White label & branding",
    "planPartnerF5": "✓ Dedicated onboarding",
    "planPartnerF6": "✓ Personal account manager",
    "planPartnerF7": "✓ 99.9% SLA uptime",
    "planPartnerF8": "✓ Co‑branded reports",
    "faqQ1": "Do I need to install anything?",
    "faqA1": "No. Verdant is 100% web and mobile.",
    "faqQ2": "Is my data secure?",
    "faqA2": "GDPR‑aligned design, EU hosting options, encryption at rest with your cloud provider.",
    "faqQ3": "Does it work without an ERP?",
    "faqA3": "Yes — upload Excel or enter data manually.",
    "faqQ4": "Can I cancel anytime?",
    "faqA4": "Yes, no lock‑in: cancel in one click from the portal.",
    "faqQ5": "Does CSRD apply to my company?",
    "faqA5": "From 2026 it concerns many SMEs above ~250 employees or ~€40M turnover — validate legally for your case.",
    "faqQ6": "Do you offer support?",
    "faqA6": "In‑app chat, email, and onboarding calls included from Growth.",
    "finalCtaTitle": "Start today. Penalties won’t wait.",
    "finalCtaSub": "14 days free, no credit card.",
    "finalCtaButton": "Create your account",
    "finalCtaTrust": "SSL • GDPR • EU hosting • Cancel anytime",
    "footerTagline": "ESG compliance in 5 minutes. Not in 5 months.",
    "footerFeatures": "Features",
    "footerPricing": "Pricing",
    "footerLogin": "Log in",
    "footerCopyright": "© {year} Verdant. All rights reserved.",
    "@footerCopyright": {"placeholders": {"year": {}}},
    "featuresHeroTitle": "From CO₂ measurement to signed reports",
    "loginTitle": "Welcome back to Verdant",
    "loginNoAccount": "No account?",
    "loginRegisterCta": "Sign up free →",
    "loginEmail": "Email",
    "loginEmailHint": "name@company.com",
    "loginPassword": "Password",
    "loginForgot": "Forgot password?",
    "loginSubmit": "Log in",
    "loginSubmitLoading": "Signing in…",
    "loginGoogle": "Continue with Google",
    "errSupabaseLogin": "Configure Supabase with --dart-define to sign in.",
    "errLoginFailed": "Sign‑in failed. Check your credentials.",
    "errOAuth": "OAuth requires a configured Supabase project.",
    "registerTitle": "Start your 14‑day free trial",
    "registerSubtitle": "No credit card required",
    "registerCompany": "Company name",
    "registerEmail": "Business email",
    "registerPassword": "Password",
    "registerSector": "Sector",
    "registerSize": "Company size",
    "registerTerms": "I accept the Terms and Privacy Policy",
    "registerSubmit": "Create account",
    "registerSubmitLoading": "Creating account…",
    "registerHasAccount": "Already have an account? Log in",
    "errTerms": "Accept the Terms and Privacy Policy to continue.",
    "errSupabaseRegister": "Configure Supabase with --dart-define.",
    "errRegisterFailed": "Registration failed. Try again.",
    "sectorManufacturing": "Manufacturing",
    "sectorRetail": "Retail",
    "sectorServices": "Services",
    "sectorOther": "Other",
    "sizeUnder50": "<50 employees",
    "size50to250": "50–250 employees",
    "sizeOver250": ">250 employees",
    "forgotTitle": "Reset password",
    "forgotSubmit": "Send link",
    "forgotBack": "Back to login",
    "forgotMessage": "Check your email for the reset link.",
    "errConfigureSupabase": "Configure Supabase.",
    "validatorEmailRequired": "Enter email",
    "validatorEmailInvalid": "Invalid email",
    "validatorPasswordRequired": "Enter password",
    "validatorPasswordShort": "Minimum 8 characters",
    "validatorRequiredWithLabel": "{label} is required",
    "@validatorRequiredWithLabel": {"placeholders": {"label": {}}},
    "labelField": "Field",
    "labelCompany": "Company",
    "onboardingTitle": "Onboarding • {step}/5",
    "@onboardingTitle": {"placeholders": {"step": {}}},
    "onboardingBack": "Back",
    "onboardingNext": "Next",
    "onboardingFinish": "Done",
    "onbWelcomeTitle": "Welcome to Verdant 👋",
    "onbWelcomeSub": "Let’s set up your company in 2 minutes.",
    "onbVat": "VAT ID",
    "onbVatHint": "IT01234567890",
    "onbLegalName": "Legal name",
    "onbAddress": "Headquarters",
    "onbCountry": "Country",
    "countryIT": "Italy",
    "countryDE": "Germany",
    "countryFR": "France",
    "onbDemoNote": "Demo: no real registry API call in this build.",
    "onbSectorTitle": "Your sector",
    "onbSectorManufacturing": "Manufacturing",
    "onbSectorLogistics": "Logistics",
    "onbSectorRetail": "Retail",
    "onbSectorFood": "Food",
    "onbSectorConstruction": "Construction",
    "onbSectorEnergy": "Energy",
    "onbSectorServices": "Professional services",
    "onbSectorOther": "Other",
    "onbStandardsTitle": "Which standards apply?",
    "stdCsrd": "CSRD (EU)",
    "stdIssb": "ISSB (global)",
    "stdCdp": "CDP",
    "stdGri": "GRI",
    "stdEcovadis": "EcoVadis",
    "stdUnknown": "Not sure yet",
    "onbDataTitle": "First data points",
    "onbEnergy2023": "Energy use 2023 (kWh)",
    "onbFleetKm2023": "Fleet km 2023",
    "onbEmployees": "Employees",
    "onbDataHint": "You can add details later from emissions.",
    "onbPlanTitle": "Choose a plan",
    "onbPlanSub": "Or start 14 days free on Growth.",
    "onbPlanTrial": "Growth trial (demo)",
    "onbPlanPaid": "Go to Stripe checkout",
    "dashTitle": "Dashboard",
    "dashBreadcrumb": "home / overview",
    "dashLoadingError": "Could not load dashboard",
    "dashEsgCardTitle": "ESG score",
    "dashEsgDelta": "+5 vs last year",
    "dashCo2Title": "Total CO₂",
    "dashCo2Delta": "-12% vs 2022",
    "dashCo2TonsFmt": "{value} t",
    "@dashCo2TonsFmt": {"placeholders": {"value": {}}},
    "dashReportsTitle": "Reports generated",
    "dashReportsLeft": "{n} left on plan",
    "@dashReportsLeft": {"placeholders": {"n": {}}},
    "dashBreakdownTitle": "Breakdown",
    "catEnergy": "Energy",
    "catTransport": "Transport",
    "catSuppliers": "Suppliers",
    "catOther": "Other",
    "dashRecentReports": "Latest reports",
    "dashSeeAll": "See all",
    "dashAlerts": "Compliance alerts",
    "dashSeeAllArrow": "See all →",
    "reportRow1Title": "CSRD 2024 — Draft",
    "reportRow2Title": "ISSB climate",
    "reportRow3Title": "CDP responses",
    "reportsRowMeta": "{standard} • {year}",
    "@reportsRowMeta": {"placeholders": {"standard": {}, "year": {}}},
    "authBulletGdpr": "GDPR compliant",
    "authBulletCompanies": "340+ companies already trust Verdant",
    "authBulletSetup": "Set up in 5 minutes",
    "alertRow1Title": "Missing Scope 3 data — supplier A",
    "alertRow1Sub": "Due Nov 30",
    "alertRow2Title": "EU taxonomy update",
    "alertRow2Sub": "Review in Q1",
    "quickActionsTitle": "Quick actions",
    "qaAddEmissions": "Add emissions",
    "qaGenReport": "Generate report",
    "qaUploadExcel": "Upload Excel",
    "qaConnectErp": "Connect ERP",
    "complianceTitle": "Compliance",
    "standardsSectionTitle": "Standards",
    "alertsSectionTitle": "Alerts",
    "stdCsrdTitle": "CSRD",
    "stdCsrdSub": "EU — Corporate Sustainability Reporting Directive",
    "stdIssbTitle": "ISSB",
    "stdIssbSub": "Global — IFRS Sustainability Disclosure",
    "stdSecTitle": "SEC",
    "stdSecSub": "US — climate disclosures (if applicable)",
    "compAlert1Title": "CSRD reporting",
    "compAlert1Sub": "Validate data scope",
    "compAlert2Title": "CDP questionnaire",
    "compAlert2Sub": "Supplier deadline",
    "badgeCritical": "Critical",
    "badgeWarning": "Warning",
    "complianceCardTitle": "Compliance",
    "complianceCsrdProgress": "CSRD: in progress",
    "complianceDeadline": "Deadline: Dec 2025",
    "emissionsChartTitle": "CO₂ emissions",
    "chartModeMonth": "M",
    "chartModeQuarter": "Q",
    "chartModeYear": "Y",
    "scope1": "Scope 1",
    "scope2": "Scope 2",
    "scope3": "Scope 3",
    "emissionsUploadTitle": "Data & emissions",
    "tabUploadExcel": "Excel upload",
    "tabManual": "Manual",
    "tabIntegrations": "Integrations",
    "dropExcelTitle": "Drop your Excel file here",
    "dropExcelPick": "or choose a file",
    "mappingTitle": "Column mapping",
    "mappingColExcel": "Excel column",
    "mappingColVerdant": "Verdant field",
    "mappingImport": "Import & calculate CO₂",
    "snackCalculating": "Calculating… (demo)",
    "fieldKwh": "kWh",
    "fieldLitersDiesel": "Diesel litres",
    "fieldKm": "km",
    "manualTitle": "Manual entry",
    "manualFullTitle": "Manual entry",
    "manualCategory": "Category",
    "manualKwh": "kWh",
    "manualKm": "km",
    "manualDieselL": "Diesel litres",
    "manualAdd": "Add record",
    "unitCo2eKg": "kg CO₂e",
    "manualRecords": "Records",
    "catEnergyOpt": "Energy",
    "catTransportOpt": "Transport",
    "catGas": "Gas",
    "catWater": "Water",
    "catWaste": "Waste",
    "catSuppliersOpt": "Suppliers",
    "integrationsOpenDetail": "Open Integrations from the menu for details.",
    "integrationsTitle": "Integrations",
    "integConnect": "Connect",
    "integOAuth": "OAuth",
    "integGenApiKey": "Generate API key",
    "reportsListTitle": "ESG reports",
    "reportsNew": "New report",
    "reportGenTitle": "Generate report",
    "stepConfig": "1. Config",
    "stepPreview": "2. Preview",
    "stepOutput": "3. Output",
    "fieldYear": "Year",
    "fieldStandard": "Standard",
    "fieldReportLang": "Report language",
    "toggleBenchmark": "Sector benchmark",
    "toggleImprovement": "Improvement plan",
    "reportForward": "Next",
    "reportBack": "Back",
    "reportDataCompleteness": "Data completeness",
    "reportMissingScope3": "Missing: Scope 3 tier‑1 suppliers",
    "reportAddNow": "Add now →",
    "reportGenerating": "Generating…",
    "reportGenerateBtn": "Generate {standard} report",
    "@reportGenerateBtn": {"placeholders": {"standard": {}}},
    "reportPreviewPdf": "Preview / print PDF",
    "genStepCollect": "Collecting data…",
    "genStepCalc": "Calculating emissions…",
    "genStepCompliance": "Checking compliance…",
    "genStepPdf": "Building PDF…",
    "genStepDone": "Report ready",
    "settingsTitle": "Settings",
    "settingsCompany": "Company profile",
    "settingsBilling": "Stripe billing",
    "settingsManualFull": "Manual entry (full page)",
    "signOut": "Sign out",
    "companyProfileTitle": "Company profile",
    "fieldLegalName": "Legal name",
    "fieldVat": "VAT ID",
    "fieldWebsite": "Website",
    "hintLegalDemo": "Demo SpA",
    "hintVatDemo": "IT00000000000",
    "hintWebsite": "https://",
    "billingTitle": "Billing",
    "billingCurrent": "Current plan",
    "billingRenewExample": "Growth • renews 12/12/2026",
    "billingManagePortal": "Manage plan (Customer Portal)",
    "snackPortalEdge": "Connect an Edge Function that returns a portal session URL.",
    "billingPayment": "Payment method",
    "billingCardMask": "Card •••• 4242 • exp 12/28",
    "billingUpdateCard": "Update method",
    "billingInvoices": "Invoices",
    "invoiceExample": "€299 • 01/03/2026",
    "billingDanger": "Danger zone",
    "billingCancelSub": "Cancel subscription",
    "dialogCancelTitle": "Cancel subscription?",
    "dialogRequestSent": "Request sent (demo).",
    "featuresPageSubtitle": "From measurement to compliance",
    "pricingPageTitle": "Pricing",
    "stateErrorSupabase": "Supabase not configured. Use --dart-define.",
    "pdfFooter": "Generated with Verdant ESG Platform • {date}",
    "@pdfFooter": {"placeholders": {"date": {}}},
    "pdfCoverTitle": "ESG report — {standard}",
    "@pdfCoverTitle": {"placeholders": {"standard": {}}},
    "pdfCompany": "Company: {name}",
    "@pdfCompany": {"placeholders": {"name": {}}},
    "pdfYear": "Year: {year}",
    "@pdfYear": {"placeholders": {"year": {}}},
    "pdfExecSummary": "Executive summary",
    "pdfBulletScore": "Overall ESG score: {score}/100",
    "@pdfBulletScore": {"placeholders": {"score": {}}},
    "pdfBulletCo2": "Total emissions estimate: {tons} t CO₂e",
    "@pdfBulletCo2": {"placeholders": {"tons": {}}},
    "pdfScopeTableTitle": "Emissions by scope",
    "pdfScopeColScope": "Scope",
    "pdfScopeColTons": "t CO₂e",
    "pdfScopeDash": "—",
    "statusDraft": "draft",
    "statusInReview": "in_review",
    "statusPublished": "published",
    "demoCompanyName": "Demo SpA",
    "colColumnA": "Column A",
    "colColumnB": "Column B",
}


def merge(locale: str, overrides: dict) -> dict:
    d = copy.deepcopy(EN)
    d["@@locale"] = locale
    for k, v in overrides.items():
        d[k] = v
    return d


def arb_sort_keys(d: dict) -> dict:
    keys = [k for k in d if not k.startswith("@")]
    meta = [k for k in d if k.startswith("@")]
    keys.sort()
    meta.sort()
    out = {"@@locale": d["@@locale"]}
    for k in keys:
        out[k] = d[k]
    for k in meta:
        out[k] = d[k]
    return out


def write_arb(locale: str, d: dict) -> None:
    os.makedirs(DIR, exist_ok=True)
    path = os.path.join(DIR, f"app_{locale}.arb")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(arb_sort_keys(d), f, ensure_ascii=False, indent=2)
        f.write("\n")


# Full Italian UI (complete translation of EN keys)
IT = {
    "account": "Account",
    "language": "Lingua",
    "searchHint": "Cerca…",
    "back": "Indietro",
    "next": "Avanti",
    "done": "Fine",
    "forward": "Continua",
    "save": "Salva",
    "or": "oppure",
    "yes": "Sì",
    "no": "No",
    "monthly": "Mensile",
    "yearlyWithDiscount": "Annuale (-20%)",
    "billing": "Fatturazione",
    "perMonth": "/mese",
    "perMonthAnnual": "/mese (fatturato annualmente)",
    "langName_en": "Inglese", "langName_it": "Italiano", "langName_fr": "Francese", "langName_de": "Tedesco",
    "langName_zh": "Cinese", "langName_ru": "Russo", "langName_uk": "Ucraino", "langName_he": "Ebraico", "langName_fa": "Persiano",
    "langName_es": "Spagnolo", "langName_pt": "Portoghese", "langName_ar": "Arabo", "langName_ja": "Giapponese", "langName_ko": "Coreano",
    "langName_nl": "Olandese", "langName_pl": "Polacco", "langName_tr": "Turco", "langName_hi": "Hindi", "langName_sv": "Svedese", "langName_el": "Greco",
    "navEmissions": "Dati e emissioni", "navReports": "Report ESG", "navIntegrations": "Integrazioni", "navSettings": "Impostazioni",
    "navShortDashboard": "Home", "navShortData": "Dati", "navShortReports": "Report", "navShortCompliance": "Norme", "navShortIntegrations": "App",
    "planStarterSidebar": "Piano Starter", "reportsUsedProgress": "{used}/{total} report usati", "upgradeGrowth": "Passa a Growth",
    "landingFeatures": "Funzionalità", "landingPricing": "Prezzi", "landingLogin": "Accedi", "landingTryFree": "Prova gratis",
    "heroHeadline": "Conformità ESG\nin 5 minuti.\nNon in 5 mesi.",
    "heroSub": "Verdant calcola le emissioni CO₂, genera report CSRD e riduce il rischio sanzioni.",
    "heroCtaFree": "Inizia gratis — 14 giorni", "heroCtaDemo": "Guarda demo →", "heroBadgeCsrd": "Conforme CSRD 2025",
    "heroSocialProof": "Già usato da oltre 340 PMI europee", "heroScopeCsrd": "CSRD ✓", "heroScope1": "Scope 1 ✓", "heroScope2": "Scope 2 ✓",
    "problemTitle": "Il caos ESG che vivi oggi", "problem1Title": "Dati sparsi ovunque",
    "problem1Body": "Excel, email, PDF, ERP: nessun sistema unico.", "problem2Title": "Standard incomprensibili",
    "problem2Body": "CSRD, ISSB, GRI, CDP: ogni volta una lingua diversa.", "problem3Title": "Consulenti a €200/ora",
    "problem3Body": "Per report che la normativa aggiorna ogni anno.", "problemWarning": "Dal 2026 sanzioni CSRD fino al 2% del fatturato",
    "solutionTitle": "Tutto ciò che ti serve.", "solTabCo2": "📊 Calcola CO₂", "solTabReport": "📄 Genera report",
    "solTabAlerts": "🔔 Avvisi normativi", "solTabIntegrate": "🔌 Integrazioni",
    "solCo2Kwh": "kWh energia", "solReportPreviewTitle": "Anteprima report", "solReportExportDemo": "Export PDF (demo)",
    "snackDownloadSimulated": "Download simulato", "severityCritical": "Critico", "severityAttention": "Attenzione", "severityInfo": "Info",
    "integNameFic": "Fatture in cloud", "integStatusConnected": "Connesso ✓", "integStatusAvailable": "Disponibile", "integStatusSoon": "Prossimamente",
    "socialTitle": "Le opinioni delle PMI", "pricingTransparent": "Prezzi trasparenti", "pricingSubtitle": "Scegli un piano e scala.",
    "pricingEnterprise": "Oltre 1000 dipendenti? Contattaci.", "pricingPaySecure": "Pagamento sicuro Stripe • Fattura elettronica",
    "planCtaStartTrial": "Inizia prova 14 giorni", "planCtaContactSales": "Contatta vendite", "planBadgePopular": "Più scelto", "planBadgePartner": "Per studi e consulenti",
    "finalCtaTitle": "Inizia oggi. Le sanzioni non aspettano.", "finalCtaSub": "14 giorni gratis, senza carta.", "finalCtaButton": "Crea account",
    "finalCtaTrust": "SSL • GDPR • Hosting UE • Disdici quando vuoi", "footerTagline": "ESG in 5 minuti, non in 5 mesi.",
    "footerFeatures": "Funzionalità", "footerPricing": "Prezzi", "footerLogin": "Accedi", "footerCopyright": "© {year} Verdant. Tutti i diritti riservati.",
    "featuresHeroTitle": "Dal calcolo CO₂ al report firmato", "loginTitle": "Bentornato su Verdant", "loginNoAccount": "Non hai un account?",
    "loginRegisterCta": "Registrati gratis →", "loginSubmit": "Accedi", "loginSubmitLoading": "Accesso…", "loginGoogle": "Continua con Google",
    "errSupabaseLogin": "Configura Supabase (--dart-define).", "errLoginFailed": "Credenziali non valide.", "errOAuth": "OAuth richiede Supabase.",
    "registerTitle": "14 giorni gratis", "registerSubtitle": "Senza carta di credito", "registerCompany": "Ragione sociale",
    "registerTerms": "Accetto Termini e Privacy", "registerSubmit": "Crea account", "registerSubmitLoading": "Creazione in corso…",
    "registerHasAccount": "Hai già un account? Accedi", "errTerms": "Accetta Termini e Privacy.", "errSupabaseRegister": "Configura Supabase.",
    "errRegisterFailed": "Registrazione non riuscita.", "forgotTitle": "Recupero password", "forgotSubmit": "Invia link", "forgotBack": "Torna al login",
    "forgotMessage": "Controlla la posta.", "errConfigureSupabase": "Configura Supabase.",
    "validatorEmailRequired": "Inserisci email", "validatorEmailInvalid": "Email non valida", "validatorPasswordRequired": "Inserisci password",
    "validatorPasswordShort": "Minimo 8 caratteri", "validatorRequiredWithLabel": "{label} obbligatorio", "labelCompany": "Azienda",
    "onboardingTitle": "Onboarding • {step}/5", "onbWelcomeTitle": "Benvenuto in Verdant 👋", "onbWelcomeSub": "Configuriamo l’azienda in 2 minuti.",
    "onbVat": "P.IVA", "onbLegalName": "Ragione sociale", "onbAddress": "Sede", "onbCountry": "Paese", "countryIT": "Italia", "countryDE": "Germania", "countryFR": "Francia",
    "onbDemoNote": "Demo: nessuna API reale al Registro.", "onbSectorTitle": "Settore", "onbStandardsTitle": "Quali standard ti riguardano?",
    "onbDataTitle": "Primi dati", "onbPlanTitle": "Scegli il piano", "onbPlanSub": "Oppure 14 giorni gratis su Growth.", "onbPlanTrial": "Trial Growth (demo)",
    "onbPlanPaid": "Vai a Stripe checkout", "dashTitle": "Dashboard", "dashBreadcrumb": "home / panoramica", "dashLoadingError": "Errore di caricamento",
    "dashEsgDelta": "+5 vs anno scorso", "dashCo2Title": "CO₂ totale", "dashCo2TonsFmt": "{value} t",
    "dashReportsTitle": "Report generati", "dashSeeAll": "Vedi tutti",
    "dashSeeAllArrow": "Vedi tutti →", "dashAlerts": "Avvisi compliance", "emissionsUploadTitle": "Dati e emissioni", "tabUploadExcel": "Carica Excel",
    "dropExcelTitle": "Trascina qui il file Excel", "dropExcelPick": "oppure seleziona file", "mappingTitle": "Mapping colonne",
    "mappingColExcel": "Colonna Excel", "mappingColVerdant": "Campo Verdant", "mappingImport": "Importa e calcola CO₂", "snackCalculating": "Calcolo… (demo)",
    "integrationsOpenDetail": "Vai al menu Integrazioni.", "integrationsTitle": "Integrazioni", "integConnect": "Connetti", "integGenApiKey": "Genera API key",
    "reportsListTitle": "Report ESG", "reportsNew": "Nuovo report", "reportGenTitle": "Genera report", "settingsTitle": "Impostazioni",
    "settingsCompany": "Profilo azienda", "settingsBilling": "Fatturazione Stripe", "settingsManualFull": "Inserimento manuale (pagina intera)",
    "signOut": "Esci", "companyProfileTitle": "Profilo azienda", "billingTitle": "Fatturazione", "billingDanger": "Zona pericolosa",
    "billingCancelSub": "Disdici abbonamento", "dialogCancelTitle": "Disdici abbonamento?", "dialogRequestSent": "Richiesta inviata (demo).",
    "complianceTitle": "Compliance", "standardsSectionTitle": "Standard", "alertsSectionTitle": "Avvisi", "complianceCsrdProgress": "CSRD: in corso",
    "complianceDeadline": "Scadenza: dic 2025", "emissionsChartTitle": "Emissioni CO₂", "chartModeQuarter": "T",
    "pricingPageTitle": "Prezzi", "stateErrorSupabase": "Supabase non configurato.",
    "authBulletGdpr": "Conforme GDPR",
    "authBulletCompanies": "Oltre 340 aziende scelgono Verdant",
    "authBulletSetup": "Configurazione in 5 minuti",
}

# Auto-fill IT: for any key not in IT, keep from EN — we merge IT into EN base
def full_locale(code: str, ov: dict) -> dict:
    d = copy.deepcopy(EN)
    d["@@locale"] = code
    for k, v in ov.items():
        d[k] = v
    return d


def main() -> None:
    locales = {
        "en": {},
        "it": IT,
        "fr": {
            "language": "Langue", "heroHeadline": "Conformité ESG\nen 5 minutes.\nPas en 5 mois.",
            "heroSub": "Verdant calcule vos émissions CO₂ et génère des rapports CSRD.",
            "landingLogin": "Connexion", "landingFeatures": "Fonctions", "landingPricing": "Tarifs", "loginTitle": "Bon retour chez Verdant",
            "navEmissions": "Données et émissions", "back": "Retour", "next": "Suivant", "settingsTitle": "Réglages", "integrationsTitle": "Intégrations",
            "langName_en": "Anglais", "langName_it": "Italien", "langName_fr": "Français", "langName_de": "Allemand", "langName_zh": "Chinois",
            "langName_ru": "Russe", "langName_uk": "Ukrainien", "langName_he": "Hébreu", "langName_fa": "Persan", "langName_es": "Espagnol",
            "langName_pt": "Portugais", "langName_ar": "Arabe", "langName_ja": "Japonais", "langName_ko": "Coréen", "langName_nl": "Néerlandais",
            "langName_pl": "Polonais", "langName_tr": "Turc", "langName_hi": "Hindi", "langName_sv": "Suédois", "langName_el": "Grec",
            "footerCopyright": "© {year} Verdant. Tous droits réservés.",
        },
        "de": {
            "language": "Sprache", "heroHeadline": "ESG‑Compliance\nin 5 Minuten.\nNicht in 5 Monaten.",
            "heroSub": "Verdant berechnet CO₂‑Emissionen und liefert CSRD‑Berichte.",
            "landingLogin": "Anmelden", "landingFeatures": "Funktionen", "landingPricing": "Preise", "loginTitle": "Willkommen zurück bei Verdant",
            "navEmissions": "Daten & Emissionen", "back": "Zurück", "next": "Weiter", "settingsTitle": "Einstellungen",
            "langName_en": "Englisch", "langName_it": "Italienisch", "langName_fr": "Französisch", "langName_de": "Deutsch", "langName_zh": "Chinesisch",
            "langName_ru": "Russisch", "langName_uk": "Ukrainisch", "langName_he": "Hebräisch", "langName_fa": "Persisch", "langName_es": "Spanisch",
            "langName_pt": "Portugiesisch", "langName_ar": "Arabisch", "langName_ja": "Japanisch", "langName_ko": "Koreanisch", "langName_nl": "Niederländisch",
            "langName_pl": "Polnisch", "langName_tr": "Türkisch", "langName_hi": "Hindi", "langName_sv": "Schwedisch", "langName_el": "Griechisch",
            "footerCopyright": "© {year} Verdant. Alle Rechte vorbehalten.",
        },
    }

    # Remaining: translate UI fully by reusing EN + native language names + headline/login
    NAMES = {
        "zh": ("语言", "英语", "意大利语", "法语", "德语", "中文", "俄语", "乌克兰语", "希伯来语", "波斯语", "西班牙语", "葡萄牙语", "阿拉伯语", "日语", "韩语", "荷兰语", "波兰语", "土耳其语", "印地语", "瑞典语", "希腊语", "登录", "数据与排放", "ESG 合规\n5 分钟。\n不用 5 个月。"),
        "ru": ("Язык", "Английский", "Итальянский", "Французский", "Немецкий", "Китайский", "Русский", "Украинский", "Иврит", "Персидский", "Испанский", "Португальский", "Арабский", "Японский", "Корейский", "Нидерландский", "Польский", "Турецкий", "Хинди", "Шведский", "Греческий", "Войти", "Данные и выбросы", "Соответствие ESG\nза 5 минут.\nНе за 5 месяцев."),
        "uk": ("Мова", "Англійська", "Італійська", "Французька", "Німецька", "Китайська", "Російська", "Українська", "Іврит", "Перська", "Іспанська", "Португальська", "Арабська", "Японська", "Корейська", "Нідерландська", "Польська", "Турецька", "Гінді", "Шведська", "Грецька", "Увійти", "Дані та викиди", "Відповідність ESG\nза 5 хвилин.\nНе за 5 місяців."),
        "he": ("שפה", "אנגלית", "איטלקית", "צרפתית", "גרמנית", "סינית", "רוסית", "אוקראינית", "עברית", "פרסית", "ספרדית", "פורטוגזית", "ערבית", "יפנית", "קוריאנית", "הולנדית", "פולנית", "טורקית", "הינדי", "שוודית", "יוונית", "כניסה", "נתונים ופליטות", "תאימות ESG\nב־5 דקות.\nלא ב־5 חודשים."),
        "fa": ("زبان", "انگلیسی", "ایتالیایی", "فرانسوی", "آلمانی", "چینی", "روسی", "اوکراینی", "عبری", "فارسی", "اسپانیایی", "پرتغالی", "عربی", "ژاپنی", "کره‌ای", "هلندی", "لهستانی", "ترکی", "هندی", "سوئدی", "یونانی", "ورود", "داده‌ها و انتشار", "انطباق ESG\nدر ۵ دقیقه.\nنه ۵ ماه."),
        "es": ("Idioma", "Inglés", "Italiano", "Francés", "Alemán", "Chino", "Ruso", "Ucraniano", "Hebreo", "Persa", "Español", "Portugués", "Árabe", "Japonés", "Coreano", "Neerlandés", "Polaco", "Turco", "Hindi", "Sueco", "Griego", "Iniciar sesión", "Datos y emisiones", "Cumplimiento ESG\nen 5 minutos.\nNo en 5 meses."),
        "pt": ("Idioma", "Inglês", "Italiano", "Francês", "Alemão", "Chinês", "Russo", "Ucraniano", "Hebraico", "Persa", "Espanhol", "Português", "Árabe", "Japonês", "Coreano", "Holandês", "Polonês", "Turco", "Hindi", "Sueco", "Grego", "Entrar", "Dados e emissões", "Conformidade ESG\nem 5 minutos.\nNão em 5 meses."),
        "ar": ("اللغة", "الإنجليزية", "الإيطالية", "الفرنسية", "الألمانية", "الصينية", "الروسية", "الأوكرانية", "العبرية", "الفارسية", "الإسبانية", "البرتغالية", "العربية", "اليابانية", "الكورية", "الهولندية", "البولندية", "التركية", "الهندية", "السويدية", "اليونانية", "تسجيل الدخول", "البيانات والانبعاثات", "الامتثال لمعايير ESG\nفي 5 دقائق.\nوليس 5 أشهر."),
        "ja": ("言語", "英語", "イタリア語", "フランス語", "ドイツ語", "中国語", "ロシア語", "ウクライナ語", "ヘブライ語", "ペルシャ語", "スペイン語", "ポルトガル語", "アラビア語", "日本語", "韓国語", "オランダ語", "ポーランド語", "トルコ語", "ヒンディー語", "スウェーデン語", "ギリシャ語", "ログイン", "データと排出量", "ESG 対応は\n5分で。\n5ヶ月ではない。"),
        "ko": ("언어", "영어", "이탈리아어", "프랑스어", "독일어", "중국어", "러시아어", "우크라이나어", "히브리어", "페르시아어", "스페인어", "포르투갈어", "아랍어", "일본어", "한국어", "네덜란드어", "폴란드어", "터키어", "힌디어", "스웨덴어", "그리스어", "로그인", "데이터 및 배출", "ESG 준수\n5분 만에.\n5개월이 아니라."),
        "nl": ("Taal", "Engels", "Italiaans", "Frans", "Duits", "Chinees", "Russisch", "Oekraïens", "Hebreeuws", "Perzisch", "Spaans", "Portugees", "Arabisch", "Japans", "Koreaans", "Nederlands", "Pools", "Turks", "Hindi", "Zweeds", "Grieks", "Inloggen", "Data & emissies", "ESG‑compliance\nin 5 minuten.\nNiet in 5 maanden."),
        "pl": ("Język", "Angielski", "Włoski", "Francuski", "Niemiecki", "Chiński", "Rosyjski", "Ukraiński", "Hebrajski", "Perski", "Hiszpański", "Portugalski", "Arabski", "Japoński", "Koreański", "Holenderski", "Polski", "Turecki", "Hindi", "Szwedzki", "Grecki", "Zaloguj", "Dane i emisje", "Zgodność ESG\nw 5 minut.\nNie w 5 miesięcy."),
        "tr": ("Dil", "İngilizce", "İtalyanca", "Fransızca", "Almanca", "Çince", "Rusça", "Ukraynaca", "İbranice", "Farsça", "İspanyolca", "Portekizce", "Arapça", "Japonca", "Korece", "Hollandaca", "Lehçe", "Türkçe", "Hintçe", "İsveççe", "Yunanca", "Giriş", "Veri ve emisyonlar", "ESG uyumu\n5 dakikada.\n5 ayda değil."),
        "hi": ("भाषा", "अंग्रेज़ी", "इटालियन", "फ़्रेंच", "जर्मन", "चीनी", "रूसी", "यूक्रेनियाई", "हिब्रू", "फ़ारसी", "स्पेनिश", "पुर्तगाली", "अरबी", "जापानी", "कोरियाई", "डच", "पोलिश", "तुर्की", "हिंदी", "स्वीडिश", "ग्रीक", "लॉग इन", "डेटा और उत्सर्जन", "ESG अनुपालन\n5 मिनट में.\n5 महीने में नहीं।"),
        "sv": ("Språk", "Engelska", "Italienska", "Franska", "Tyska", "Kinesiska", "Ryska", "Ukrainska", "Hebreiska", "Persiska", "Spanska", "Portugisiska", "Arabiska", "Japanska", "Koreanska", "Nederländska", "Polska", "Turkiska", "Hindi", "Svenska", "Grekiska", "Logga in", "Data & utsläpp", "ESG‑efterlevnad\n på 5 minuter.\nInte på 5 månader."),
        "el": ("Γλώσσα", "Αγγλικά", "Ιταλικά", "Γαλλικά", "Γερμανικά", "Κινεζικά", "Ρωσικά", "Ουκρανικά", "Εβραϊκά", "Περσικά", "Ισπανικά", "Πορτογαλικά", "Αραβικά", "Ιαπωνικά", "Κορεατικά", "Ολλανδικά", "Πολωνικά", "Τουρκικά", "Χίντι", "Σουηδικά", "Ελληνικά", "Σύνδεση", "Δεδομένα & εκπομπές", "Συμμόρφωση ESG\nσε 5 λεπτά.\nΌχι σε 5 μήνες."),
    }

    def picker_ov(t: tuple) -> dict:
        return {
            "language": t[0],
            "langName_en": t[1], "langName_it": t[2], "langName_fr": t[3], "langName_de": t[4], "langName_zh": t[5],
            "langName_ru": t[6], "langName_uk": t[7], "langName_he": t[8], "langName_fa": t[9], "langName_es": t[10],
            "langName_pt": t[11], "langName_ar": t[12], "langName_ja": t[13], "langName_ko": t[14], "langName_nl": t[15],
            "langName_pl": t[16], "langName_tr": t[17], "langName_hi": t[18], "langName_sv": t[19], "langName_el": t[20],
            "landingLogin": t[21], "navEmissions": t[22], "heroHeadline": t[23],
        }

    for code, t in NAMES.items():
        locales[code] = picker_ov(t)

    for code, ov in locales.items():
        write_arb(code, full_locale(code, ov))

    print(f"Wrote {len(locales)} ARB files to {DIR}")


if __name__ == "__main__":
    main()
